# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '22 5 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Questa issue è inattiva da molto tempo, considera continuare a lavorarci o chiudila'
        stale-pr-message: 'Questa pull-request è inattiva da molto tempo, considera continuare a lavorarci o chiudila'
        stale-issue-label: 'Questa issue è marcata come "stale" considera chiuderla'
        stale-pr-label: 'Questa pull-request non ha attività, considera discuterne o continuare a lavorarci'
